---
- name: Install metricbeat from deb file 
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-5.6.3-amd64.deb

- name: start and enable metricbeat
  service:
    name: metricbeat
    state: started
    enabled: true